/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_DD1;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin-Alex
 */
public class hacerReserva extends javax.swing.JDialog {
    private verReservas verreservas;
    /**
     * Creates new form reserva
     */
    public hacerReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        verreservas = (verReservas)parent;
        
        initComponents();
        
    }

    private boolean validarFormulario() {

        String nombre = jTextField_nombre.getText();
        if (nombre == null || "".equals(nombre)) {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        String apellidos = jTextField_apellidos.getText();
        if (apellidos == null || "".equals(apellidos)) {
            JOptionPane.showMessageDialog(this, "El apellido no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        Date fecha = (Date)jSpinner_fecha.getValue();
        if (fecha == null || "".equals(fecha)) {
            JOptionPane.showMessageDialog(this, "La fecha no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        String oficina = (String)jComboBox_oficina.getSelectedItem();

        if (oficina == null || "".equals(oficina)) {
            JOptionPane.showMessageDialog(this, "La oficina no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        String mesa = (String)jComboBox_mesa.getSelectedItem();
        if (mesa == null || "".equals(mesa)) {
            JOptionPane.showMessageDialog(this, "La mesa no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_fecha = new javax.swing.JSpinner();
        jComboBox_oficina = new javax.swing.JComboBox<>();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_apellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_mesa = new javax.swing.JComboBox<>();
        jButton_reservar = new javax.swing.JButton();
        jButton_borrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTextField3.setText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jTextField3.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 7, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jLabel3.text")); // NOI18N
        jLabel3.setToolTipText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jLabel3.toolTipText")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jSpinner_fecha.setModel(new javax.swing.SpinnerDateModel());
        jSpinner_fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        getContentPane().add(jSpinner_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 240, 30));

        jComboBox_oficina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_oficina, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 99, -1));

        jTextField_nombre.setText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jTextField_nombre.text")); // NOI18N
        jTextField_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 164, 20));

        jTextField_apellidos.setText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jTextField_apellidos.text")); // NOI18N
        jTextField_apellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jTextField_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_apellidosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jLabel4.text")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jLabel5.text")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, -1));

        jComboBox_mesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 99, -1));

        jButton_reservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        jButton_reservar.setText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jButton_reservar.text")); // NOI18N
        jButton_reservar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jButton_reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reservarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 80, 37));

        jButton_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        jButton_borrar.setText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jButton_borrar.text")); // NOI18N
        jButton_borrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jButton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 220, 70, 37));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oficina.jpg"))); // NOI18N
        jLabel6.setText(org.openide.util.NbBundle.getMessage(hacerReserva.class, "hacerReserva.jLabel6.text")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    private void jButton_reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reservarActionPerformed
        if (validarFormulario()) {
        String nombre = jTextField_nombre.getText();
        String apellidos = jTextField_apellidos.getText();
        Date fecha = (Date)jSpinner_fecha.getValue();
        String oficina = (String)jComboBox_oficina.getSelectedItem();
        String mesa = (String)jComboBox_mesa.getSelectedItem();
        Reserva reserva =new Reserva(nombre, apellidos, fecha, oficina, mesa);
        verreservas.añadirReserva(reserva);
        JOptionPane.showMessageDialog(this, "Reserva a nombre de: " + nombre +" "+ apellidos);
        dispose();   
            

        }
        
        
             
    }//GEN-LAST:event_jButton_reservarActionPerformed

    private void jTextField_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_apellidosActionPerformed

    private void jButton_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_borrarActionPerformed
        jTextField_nombre.setText(null);
        jTextField_apellidos.setText(null);
        jSpinner_fecha.setValue(null);
        jComboBox_oficina.setSelectedItem(null);
        jComboBox_mesa.setSelectedItem(null);
    }//GEN-LAST:event_jButton_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hacerReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hacerReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hacerReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hacerReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                hacerReserva dialog = new hacerReserva(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_borrar;
    private javax.swing.JButton jButton_reservar;
    private javax.swing.JComboBox<String> jComboBox_mesa;
    private javax.swing.JComboBox<String> jComboBox_oficina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner jSpinner_fecha;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField_apellidos;
    private javax.swing.JTextField jTextField_nombre;
    // End of variables declaration//GEN-END:variables
}
