/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_DD1;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;




/**
 *
 * @author Admin-Alex
 */
public class iniciar_sesion extends javax.swing.JFrame {

    /**
     * Creates new form iniciar_sesion
     */
    FondoPanel fondo= new FondoPanel();
    
   
    public iniciar_sesion() {
    
        
        initComponents();
        //Icono:  
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource(""));
        setIconImage(iconoPropio);
        setVisible(true);
        // Validaciones con Validation Panel:
        ValidationGroup group1 = validationPanel1.getValidationGroup();
        group1.add(jTextField_usuario_correo, StringValidators.REQUIRE_NON_EMPTY_STRING);
        ValidationGroup group2 = validationPanel2.getValidationGroup();
        group2.add(jPasswordField_contraseña, StringValidators.REQUIRE_NON_EMPTY_STRING);
        
        this.getContentPane().setBackground(Color.green);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validationPanel3 = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_usuario_correo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton_iniciar_sesion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        validationPanel2 = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jPasswordField_contraseña = new javax.swing.JPasswordField();
        jLabel_icon_correo = new javax.swing.JLabel();
        jLabel_icon_contraseña = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setBackground(new java.awt.Color(51, 153, 0));
        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIAR SESION");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 100));
        getContentPane().add(jLabel1);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Correo");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(70, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(70, 17));
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, 308, 39));

        jTextField_usuario_correo.setBackground(new java.awt.Color(51, 255, 0));
        jTextField_usuario_correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_usuario_correo.setToolTipText("");
        jTextField_usuario_correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jTextField_usuario_correo.setPreferredSize(new java.awt.Dimension(300, 20));
        jTextField_usuario_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usuario_correoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_usuario_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 56, 256, 32));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contraseña");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setInheritsPopupMenu(false);
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 129, 308, 36));

        jButton_iniciar_sesion.setText("Iniciar Sesión");
        jButton_iniciar_sesion.setHideActionText(true);
        jButton_iniciar_sesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_iniciar_sesion.setPreferredSize(new java.awt.Dimension(250, 23));
        jButton_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iniciar_sesionActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 266, -1, -1));

        jButton2.setText("Registrarme");
        jButton2.setToolTipText("");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPreferredSize(new java.awt.Dimension(100, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 300, -1, -1));

        validationPanel1.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.add(validationPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 94, 256, -1));

        validationPanel2.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.add(validationPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 214, 256, -1));

        jPasswordField_contraseña.setBackground(new java.awt.Color(51, 255, 0));
        jPasswordField_contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_contraseña.setToolTipText("");
        jPasswordField_contraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jPasswordField_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_contraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 171, 256, 32));

        jLabel_icon_correo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/correo.png"))); // NOI18N
        jPanel1.add(jLabel_icon_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 56, 34, -1));

        jLabel_icon_contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contraseña.png"))); // NOI18N
        jPanel1.add(jLabel_icon_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 171, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oficina.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 330));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_usuario_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usuario_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usuario_correoActionPerformed

    private void jButton_iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iniciar_sesionActionPerformed
        String nombre = jTextField_usuario_correo.getText();
        JOptionPane.showMessageDialog(this, "Hola " + nombre);
        inicio abrir = new inicio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_iniciar_sesionActionPerformed

    private void jPasswordField_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_contraseñaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        registro abrir1 = new registro();
        abrir1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iniciar_sesion().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_iniciar_sesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_icon_contraseña;
    private javax.swing.JLabel jLabel_icon_correo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_contraseña;
    private javax.swing.JTextField jTextField_usuario_correo;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel2;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel3;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Imagenes/fondo.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
